-- Trivia schema + seed data (cleaned)

BEGIN;

-- Drop existing objects (so re-running doesn't fail)
DROP TABLE IF EXISTS public.questions;

DROP TABLE IF EXISTS public.categories;

-- Tables
CREATE TABLE public.categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT
);

CREATE TABLE public.questions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT,
    answer TEXT,
    difficulty integer,
    category integer REFERENCES public.categories (id) ON UPDATE CASCADE ON DELETE SET NULL
);

